### ISSUE TITLE
base64Decoded adds unexpected characters at end

### ISSUE THREAD

**Issue by sudansh** [saschpe/Kase64#20]
Given assert fails 

> assertEquals(
>             "{\"aud\":\"ae.rain.com\",\"exp\":1713261313,\"iat\":1713259513,\"iss\":\"ae.rain.com\",\"rain:jurisdiction\":\"uae\",\"sub\":\"58490195-01b9-4dcf-ae28-ae0b20f8fbda\"}",
>             "eyJhdWQiOiJhZS5yYWluLmNvbSIsImV4cCI6MTcxMzI2MTMxMywiaWF0IjoxNzEzMjU5NTEzLCJpc3MiOiJhZS5yYWluLmNvbSIsInJhaW46anVyaXNkaWN0aW9uIjoidWFlIiwic3ViIjoiNTg0OTAxOTUtMDFiOS00ZGNmLWFlMjgtYWUwYjIwZjhmYmRhIn0".base64Decoded
>         )

**Comment by saschpe** [comment]
Try `"ey...n0".base64UrlDecoded` :-)
