### ISSUE TITLE
The package "saschpe.kase64" is empty.

### ISSUE THREAD

**Issue by YuryMikhailuts** [saschpe/Kase64#5]
I connected the library to the kotlin multiplatform project, but the package `saschpe.kase64` is empty.

![image](https://user-images.githubusercontent.com/48589388/175394695-6653c543-68fa-4a1c-84d5-d8aff9cfbf01.png)

**Comment by saschpe** [comment]
Could that be an IntelliJ indexing issue? We are using the lib in multiple projects with success. Which version do you use?

**Comment by YuryMikhailuts** [comment]
The index is definitely fine. I've reset it several times. The library version is `1.0.5`. Kotlin version in the project is `1.6.20`. gradle version is `7.4.2`.

**Comment by saschpe** [comment]
How does it look like in IntelliJ's dependencies list in the project tool window? It should be something like:

<img width="335" alt="Screen Shot 2022-06-24 at 08 27 02" src="https://user-images.githubusercontent.com/115275/175475792-26b7ecab-cd8f-46b9-bc14-745dd90279b0.png">

It could also be an issue with your multiplatform project configuration.

**Comment by YuryMikhailuts** [comment]
![image](https://user-images.githubusercontent.com/48589388/175479902-a4fd347c-5d2f-4bf5-bc49-aba197e857f6.png)

**Comment by saschpe** [comment]
So the downloaded libraries are indeed looking good. As said, it's an issue with your project configuration. Is that publicly available somewhere?

**Comment by YuryMikhailuts** [comment]
No. The project is commercial. I can't put it in open access.

**Comment by saschpe** [comment]
You could try manually putting `import saschpe.kase64.base64Encoded` into any of your code files and try to encode any String. I'd take a closer look at the project configuration. Maybe you can take inspiration from https://github.com/saschpe/Kase64/blob/main/kase64/build.gradle.kts#L8

**Comment by YuryMikhailuts** [comment]
Everything is clear. Your project requires Android. the fact is that I have a project without Android. There are two target platforms in my project: Jvm and JS.
